### ISSUE TITLE
[GraphqlDemo-1] Select Docker image for the project

### ISSUE THREAD

**Issue by michal-wybraniec** [dzbvn/Django-GraphQL#1]
First, we need to determine what operating system will be sufficient for the application's needs. The first requirement will be to base the application on the Linux operating system. Ideally, the image will not be particularly elaborate. We will expand the image ourselves with the necessary packages.
**_Please provide in the comments examples of 4 Docker images that could be useful for this project._**

**Comment by szymonklempert** [comment]
For example images of Ubuntu, Alpine, Debian and Arch Linux

**Comment by michal-wybraniec** [comment]
Could you list the advantages and disadvantages of these systems?

**Comment by szymonklempert** [comment]
Ubuntu is derived from Debian, so it is available for many architectures, while Arch Linux supports only x86 architecture. Also, Debian has over 50000 packages, although Arch is more stable than Debian distros and basically faster. Alpine Linux is commonly used for managing routers and firewalls.

**Comment by michal-wybraniec** [comment]
It has been settled. Ubuntu will be the main OS to run this application. Good choice!
